Feature/post prediction card
polkassembly/polkassembly pull request #1081
Opened 2023-12-13 19:48 UTC by adetoye-dev

2023-12-14 14:41 UTC, niklabh approved these changes

2023-12-14 14:46 UTC, niklabh commented on src/ui-components/PredictionCard/index.tsx
> +					query: `query MarketDetails($marketId: Int = 307) {
fix indentation

2023-12-14 15:12 UTC, rajdeep7Singh requested changes

2023-12-14 15:12 UTC, rajdeep7Singh commented on src/ui-components/PredictionCard/index.tsx
> +					query: `query MarketDetails($marketId: Int = 307) {
awaiting confirmation from product on this.

2024-01-06 13:13 UTC, KanishkaRajputd approved these changes

2024-01-06 13:13 UTC, merged