feat:adding Input and InputTextarea component for input and textarea fields
polkassembly/polkassembly pull request #1089
Opened 2023-12-14 17:29 UTC by jasmeets-6575

Adding Input and InputTextarea component for input and textarea fields

2023-12-14 18:57 UTC, VAIBHAV-25 commented on pages/reset-password/index.tsx
> +											<Input
type='password' parameter missing

2024-01-15 05:39 UTC, AleemAlam requested changes

2024-01-15 05:39 UTC, AleemAlam commented on src/basic-components/Input/InputTextarea.tsx
> +interface Props {
Please also extend Antd Props here

2024-01-15 05:39 UTC, AleemAlam commented on src/basic-components/Input/index.tsx
> +interface Props {
Please also extend Antd Props here

2024-01-23 08:01 UTC, AleemAlam approved these changes

2024-01-24 13:45 UTC, niklabh approved these changes

2024-01-24 13:53 UTC, merged