fix: tooltip issue and tags issue
polkassembly/polkassembly pull request #1182
Opened 2024-01-12 07:17 UTC by jasmeets-6575

2024-01-12 18:48 UTC, KanishkaRajputd approved these changes

2024-01-12 18:49 UTC, KanishkaRajputd requested changes

2024-01-12 18:49 UTC, KanishkaRajputd commented on src/components/Post/GovernanceSideBar/Motions/MotionVoteInfo.tsx
> +	// const totalPages = Math.ceil(councilVotes.length / itemsPerPage);
remove comments

2024-01-13 08:22 UTC, rajdeep7Singh approved these changes

2024-01-13 08:22 UTC, merged