delegated Balance
polkassembly/polkassembly pull request #1258
Opened 2024-02-06 10:50 UTC by KanishkaRajputd

2024-02-06 10:53 UTC, niklabh approved these changes

2024-02-09 14:26 UTC, rajdeep7Singh commented on src/components/UserProfile/TotalProfileBalances.tsx
> +					<span className='text-sm font-medium text-bodyBlue dark:text-blue-dark-high'>{parseBalance(freeBalance.add(delegatBalance).toString(), 2, true, network)}</span>
why did we add delegateBalance into freebalance and what is delegateBalance?

2024-03-18 12:56 UTC, alphainfinitus requested changes

2024-03-18 12:56 UTC, alphainfinitus commented on pages/api/v1/delegations/total-delegate-balance.ts
> +async function handler(req: NextApiRequest, res: NextApiResponse<IDelegateBalance | MessageType>) {
please add the function for api key logging

2024-03-18 12:56 UTC, alphainfinitus commented on pages/api/v1/delegations/total-delegate-balance.ts
Please do not use any here, we use typescript for a reason

2024-03-18 14:07 UTC, alphainfinitus approved these changes

2024-03-18 14:22 UTC, merged