Migrate-web3-to-ether.js
polkassembly/polkassembly pull request #1295
Opened 2024-02-15 12:58 UTC by adetoye-dev

2024-02-15 14:04 UTC, alphainfinitus commented on src/components/Post/GovernanceSideBar/Proposals/SecondProposalEth.tsx
> +		voteContract
please add an `await` here

2024-02-15 14:05 UTC, alphainfinitus commented on src/components/Post/GovernanceSideBar/Referenda/VoteReferendumEth.tsx
> +		voteContract
add an `await` here please

2024-02-15 14:06 UTC, alphainfinitus commented on next.config.js
Remove this from Prod please

2024-02-15 14:09 UTC, alphainfinitus commented on src/components/Post/GovernanceSideBar/Referenda/VoteReferendumEthV2.tsx
> +								// disabled={!wallet || !lockedBalance || isBalanceErr || lockedBalance.lte(ZERO_BN)}
please add the correct disabled state conditions

2024-02-15 14:09 UTC, alphainfinitus commented on src/components/Post/GovernanceSideBar/index.tsx
> +			contract
need an `await` here

2024-02-15 14:09 UTC, alphainfinitus commented on src/components/Settings/DemocracyUnlock.tsx
> +		contract
need an `await` here

2024-02-15 14:09 UTC, alphainfinitus commented on src/components/Settings/DemocracyUnlock.tsx
> +		contract
need an `await` here

2024-02-15 14:10 UTC, alphainfinitus commented on src/components/Settings/ReferendaUnlock.tsx
> +		contract
need an `await` here

2024-02-15 14:11 UTC, alphainfinitus commented on src/components/Settings/ReferendaUnlock.tsx
> +		contract
need an `await` here

2024-02-15 14:11 UTC, alphainfinitus commented on src/ui-components/VotesHistory.tsx
> +			contract
need an `await` here

2024-02-15 14:12 UTC, alphainfinitus requested changes
Please check comments.

2024-02-15 14:13 UTC, alphainfinitus commented on package.json
> +    "analyze": "cross-env ANALYZE=true next build",
please remove the changes related ot the bundle analyzer

2024-02-16 14:32 UTC, niklabh commented
when is this getting merged.

2024-02-19 12:48 UTC, alphainfinitus commented
Confirm button is always disabled.

2024-02-19 14:02 UTC, merged