identity optimization
polkassembly/polkassembly pull request #1603
Opened 2024-05-15 16:29 UTC by KanishkaRajputd

2024-05-23 07:26 UTC, alphainfinitus requested changes

2024-05-23 07:26 UTC, alphainfinitus commented on pages/index.tsx
>  	}, [network, api, apiReady, userId]);
we're setting network every time api or user changes.
This does not make sense.

2024-05-23 07:26 UTC, alphainfinitus commented on pages/index.tsx
> -					{isIdentityUnverified && onchainIdentitySupportedNetwork.includes(network) && (
Are we removing the warning ?

2024-05-23 07:26 UTC, alphainfinitus commented on src/components/OnchainIdentity/SocialVerificationInprogress.tsx
Are these localstorage key changes compatible with what users might already have on their localstorage ?

2024-05-24 12:57 UTC, KanishkaRajputd commented on pages/index.tsx
> -					{isIdentityUnverified && onchainIdentitySupportedNetwork.includes(network) && (
this is not mandatory

2024-05-24 12:57 UTC, KanishkaRajputd commented on src/components/OnchainIdentity/SocialVerificationInprogress.tsx
yes

2024-05-24 13:00 UTC, merged