Feat/TreasuryOverview
polkassembly/polkassembly pull request #1781
Opened 2024-07-22 05:12 UTC by jasmeets-6575

2024-08-12 06:03 UTC, KanishkaRajputd requested changes
please resolve comments

2024-08-12 06:03 UTC, KanishkaRajputd commented on src/components/Home/overviewData/LatestTreasuryOverview.tsx
> +					setGraphData(data);
balanceDifference update this state from here

2024-08-12 06:03 UTC, KanishkaRajputd commented on src/components/Home/overviewData/LatestTreasuryOverview.tsx
> +	const balanceDifference = graphData.length >= 31 ? parseFloat(graphData[graphData.length - 1].balance) - parseFloat(graphData[graphData.length - 30].balance) : null;
make it a state

2024-08-12 06:03 UTC, KanishkaRajputd commented on src/components/Home/overviewData/LatestTreasuryOverview.tsx
> +	const formatedBalanceDifference =
make it a state

2024-08-12 06:03 UTC, KanishkaRajputd commented on src/components/Home/overviewData/LatestTreasuryOverview.tsx
> +	const totalAmountUsd =
make it a state

2024-08-14 11:27 UTC, alphainfinitus requested changes

2024-08-14 11:27 UTC, alphainfinitus commented on pages/api/v1/treasury-amount-history/daily-treasury-tally.ts
> +		const response1 = await getAssetHubAndNetworkBalance(network, address1, apiUrl1);
use promise.allSettled and update the var names to have more meaning please

2024-08-14 11:27 UTC, alphainfinitus commented on pages/api/v1/treasury-amount-history/daily-treasury-tally.ts
Too many nested ifs

2024-08-14 11:27 UTC, alphainfinitus commented on pages/api/v1/treasury-amount-history/old-treasury-data.ts
same comments as above

2024-08-14 11:27 UTC, alphainfinitus commented on pages/api/v1/treasury-amount-history/old-treasury-data.ts
> +		return Object.prototype.hasOwnProperty.call(data?.monthly_treasury_tally, currentMonth);
avoid using 'hasOwnProperty' this can return true for native methods, please use "in" operator instead

2024-08-14 11:27 UTC, alphainfinitus commented on pages/api/v1/treasury-amount-history/old-treasury-data.ts
> +		return Object.prototype.hasOwnProperty.call(data?.monthly_treasury_tally, currentMonth);
this doesn't seem to handle the new year scenario.
In case of a new year, it'll show data from the last year

2024-08-15 04:23 UTC, merged