create child bounty flow
polkassembly/polkassembly pull request #2034
Opened 2024-10-14 17:27 UTC by KanishkaRajputd

2024-10-17 20:59 UTC, alphainfinitus requested changes

2024-10-17 20:59 UTC, alphainfinitus commented on pages/api/v1/child_bounties/createChildBounty.ts
> +		if (allowedCommentors && !Array.isArray(allowedCommentors)) {
please check if items in allowedCommentors are valid members of EAllowedCommentor

2024-10-17 20:59 UTC, alphainfinitus commented on pages/api/v1/child_bounties/createChildBounty.ts
> +		const newPost: Post = {
updated at key missing

2024-10-17 20:59 UTC, alphainfinitus commented on pages/api/v1/child_bounties/createChildBounty.ts
> +				return res.status(200).json({ message: 'Child Bounty successfully created, it will appear on polkassembly as soon as it is synced on chain.', post_id: postId });
no need to send message here, we can show only on FE

2024-10-17 20:59 UTC, alphainfinitus commented on styles/globals.css
> +.antSteps .ant-steps .ant-steps-item-wait .ant-steps-item-container .ant-steps-item-icon .ant-steps-icon {
these are global changes, please make sure design doesn't get messed at other places in the site

2024-10-19 10:26 UTC, AleemAlam requested changes

2024-10-19 10:26 UTC, AleemAlam commented on src/components/ChildBountyCreation/CreateChildBounty.tsx
> +								{multisigData?.threshold > 0 && <Tag className={'rounded-full bg-[#EFF0F1] px-3 py-0.5 text-xs text-[#F4970B] dark:bg-[#EFF0F1]'}>Multisig Address</Tag>}
Create a small components

2024-10-19 10:26 UTC, AleemAlam commented on src/components/ChildBountyCreation/CreateChildBounty.tsx
> +		}
check this also

2024-10-19 10:26 UTC, AleemAlam commented on src/components/ChildBountyCreation/CreateChildBounty.tsx
> +			tx = api?.tx?.multisig?.asMulti(multisigData?.threshold, multisigData?.signatories?.map((item) => item), null, tx, {
need to filter signatories

2024-10-19 10:26 UTC, AleemAlam commented on src/components/ChildBountyCreation/WriteChildBounty.tsx
> +	const { title, content, categories, allowedCommentors, link } = useChildBountyStore;
you are not calling the store

2024-10-19 10:26 UTC, AleemAlam commented on src/components/ChildBountyCreation/WriteChildBounty.tsx
> +							<Input
Dont use dispatch on onchange 
it will rerender all the component

2024-10-19 10:26 UTC, AleemAlam commented on src/components/ChildBountyCreation/WriteChildBounty.tsx
> +									dispatch(childBountyCreationActions.setContent(content?.trim()));
we have to fix this

2024-10-19 10:26 UTC, AleemAlam commented on src/components/ChildBountyCreation/index.tsx
> +		handleMultisigAddress();
remove unnecessary dependencies 
		// eslint-disable-next-line react-hooks/exhaustive-deps

2024-10-19 10:26 UTC, AleemAlam commented on src/components/Post/GovernanceSideBar/Bounty/BountyChildBounties.tsx
> +		return (
create a variable

2024-10-23 09:18 UTC, merged