Chat-with-delegates
polkassembly/polkassembly pull request #2058
Opened 2024-10-21 12:53 UTC by adetoye-dev

2024-10-24 05:41 UTC, AleemAlam requested changes

2024-10-24 05:41 UTC, AleemAlam commented on src/components/DelegationDashboard/Chat/MessageDrawer.tsx
> +				title={
can split in small components

2024-10-24 05:41 UTC, AleemAlam commented on src/components/DelegationDashboard/Chat/NewChat.tsx
> +const NewChat = ({ handleOpenChat }: Props) => {
Can split in small components

2024-10-24 05:41 UTC, AleemAlam commented on src/components/DelegationDashboard/Chat/UserChats.tsx
> +	const handleCloseChat = () => {
can create a single function for that

2024-10-24 05:41 UTC, AleemAlam commented on src/components/DelegationDashboard/Chat/index.tsx
> +				title={
Make different component for title

2024-10-24 05:41 UTC, AleemAlam commented on src/hooks/useCurrentBlock.ts
> +		api?.derive?.chain
dont use ? use early return

2024-10-24 05:41 UTC, AleemAlam commented on src/util/userProfileBalances.ts
>  		} else {
dont use ? use early return

2024-11-19 06:08 UTC, alphainfinitus requested changes
Please make sure the addresses are converted to substrate formats before comparing

2024-11-19 06:08 UTC, alphainfinitus commented on src/components/DelegationDashboard/Chat/Messages.tsx
> +						const isSent = message?.senderAddress === address;
please make sure addresses are of the same format before comparison

2024-11-20 06:43 UTC, alphainfinitus requested changes
In all apis, please make sure that we're checking for if one of the parties is a delegate or not

2024-11-20 06:43 UTC, alphainfinitus commented on pages/api/v1/delegate-chat/getChatMessages.ts
> +		const chatDoc = await chatDocRef(chatId).get();
please add a check for chatDoc.exists before checking for data, it might throw an null error

2024-11-20 08:10 UTC, alphainfinitus requested changes
Missing security checks for if request is being accepted by sender and not reciever via api

2024-11-29 12:22 UTC, alphainfinitus requested changes

2024-11-29 12:22 UTC, alphainfinitus commented on pages/api/v1/delegate-chat/getChatMessages.ts
> +	const substrateAddress = getSubstrateAddress(address);
please check if logged in user is a participant instead of the address

2024-12-03 05:10 UTC, alphainfinitus requested changes

2024-12-03 05:10 UTC, alphainfinitus commented on pages/api/v1/delegate-chat/send-message.ts
> +	const { senderAddress, receiverAddress, content, chatId, senderImage, senderUsername } = req.body;
There is no check for if any of logged in user's addresses is the same as recieved in the request body

2024-12-03 08:57 UTC, alphainfinitus requested changes

2024-12-03 08:57 UTC, alphainfinitus commented on pages/api/v1/delegate-chat/start-chat.ts
> +	const { senderAddress, receiverAddress, content, senderImage, senderUsername } = req.body;
need validation for sender image

2024-12-03 08:57 UTC, alphainfinitus commented on pages/api/v1/delegate-chat/start-chat.ts
> +				senderUsername,
we shouldn't store sender username here, because a user can change it anytime

2024-12-03 08:57 UTC, alphainfinitus commented on pages/api/v1/delegate-chat/update-request-status.ts
> +	if (chatData?.chatInitiatedBy === userSubstrateAddresses[0]) {
please add null check

2024-12-03 08:57 UTC, alphainfinitus commented on pages/api/v1/delegate-chat/update-request-status.ts
> +	if (chatData?.chatInitiatedBy === userSubstrateAddresses[0]) {
APIs and FE should have a check and nudge ensuring that a user has at least one linked address

2024-12-03 08:57 UTC, alphainfinitus commented on pages/api/v1/delegate-chat/update-request-status.ts
> +	if (!requestStatus || !chatId || !chatId.length) return res.status(400).json({ message: messages.INVALID_PARAMS });
need validation for requestStatus, the value should be from the enum

2024-12-04 14:23 UTC, alphainfinitus requested changes

2024-12-05 05:15 UTC, adetoye-dev commented on src/types.ts
> +	senderImage?: string;
we're already fetching on request for this

2024-12-06 08:57 UTC, alphainfinitus approved these changes

2024-12-11 05:12 UTC, alphainfinitus approved these changes

2024-12-11 05:12 UTC, merged