fixes
polkassembly/polkassembly pull request #260
Opened 2023-06-01 09:46 UTC by KanishkaRajputd

2023-06-01 16:48 UTC, alphainfinitus commented on cloud-functions/src/index.ts
> +    created_at: post?.created_at?.toData?.() || new Date(),
toDate instead of toData

2023-06-01 16:49 UTC, alphainfinitus commented on cloud-functions/src/index.ts
> +		objectID: `${network}_${postType}_${postId}_${commentsCount}`, // Unique identifier for the object
we don't need to rewrite the entire postObject and this is incorrect ID
this will be comment Doc that you'll get not the postDoc

2023-06-01 16:50 UTC, alphainfinitus commented on cloud-functions/src/index.ts
> +		objectID: `${network}_${postType}_${postId}_${commentsCount}`, // Unique identifier for the object
we don't need another object

2023-06-01 16:50 UTC, alphainfinitus commented on cloud-functions/src/index.ts
> +		objectID: `${network}_${postType}_${postId}_${commentsCount}`, // Unique identifier for the object
we don't need another object

2023-06-01 16:50 UTC, alphainfinitus commented on cloud-functions/src/index.ts
> +		objectID: `${network}_${postType}_${postId}_${reactionCount}`, // Unique identifier for the object
we don't need another object here

2023-06-02 13:06 UTC, alphainfinitus requested changes
Please check comments

2023-06-02 13:09 UTC, KanishkaRajputd commented on cloud-functions/src/index.ts
>  		postId,
we need it here because of redirection of the post

2023-06-05 12:44 UTC, alphainfinitus commented on cloud-functions/src/index.ts
> +		created_at: post?.created_at?.toDate?.() || new Date(),
updated_at

2023-06-05 12:49 UTC, alphainfinitus commented on cloud-functions/src/index.ts
> +		  .partialUpdateObject({[reactionData.reaction]: reactionCount, objectID:`${network}_${postType}_${postId}` })
key should be
`reaction_count : {
 [reactionData.reaction]: reactionCount
}`

2023-06-08 07:03 UTC, alphainfinitus commented on cloud-functions/src/index.ts
> +	var postRecord = {
use let instead of var please

2023-06-08 09:43 UTC, alphainfinitus commented on cloud-functions/src/index.ts
> +  const subsquidRes = fetchSubsquid({
only need to fetch subsquid data when it is  referendum v2

2023-06-08 10:35 UTC, alphainfinitus requested changes
Please check comments

2023-06-10 07:56 UTC, alphainfinitus commented on cloud-functions/src/index.ts
> +	postRecord = postType === 'ReferendumV2' ? { ...postRecord, track_number: subsquidData?.trackNumber } : postRecord;
please change the condition to `postType === 'ReferendumV2' && subsquidData`

2023-06-20 13:45 UTC, alphainfinitus commented on cloud-functions/src/utils/fetchSubsquid.ts
> +	return fetch(`${subsquidUrl}`, {
use axios for node enviroment

2023-06-20 13:49 UTC, alphainfinitus commented on cloud-functions/src/utils/fetchSubsquid.ts
> +	if (network !== ('kusama' || 'polkadot' || 'moonriver' || 'moonbeam' || 'vara') ) return;
please use (network in subsquidUrlMap)

2023-06-21 13:01 UTC, alphainfinitus approved these changes

2023-06-21 13:01 UTC, merged