logos-on-username
polkassembly/polkassembly pull request #369
Opened 2023-06-29 09:10 UTC by pathak-arpita

2023-07-04 08:55 UTC, alphainfinitus commented
<img width="208" alt="image" src="https://github.com/polkassembly/polkassembly/assets/48833948/66c040e8-124f-49c2-b987-db0a8cef2db8">
icons are too big, please match the size to design

2023-07-04 08:56 UTC, alphainfinitus commented on src/ui-components/IdentityBadge.tsx
> +		{identity?.legal && <li><span className='desc'>legal:</span><span className='text-[12px]'>{identity.legal}</span></li>}
arbitrary values being used, please used standardised font sizes

2023-07-04 08:56 UTC, alphainfinitus requested changes
Please check comments

2023-07-04 17:36 UTC, sahas-01 commented on src/ui-components/IdentityBadge.tsx
> +		{identity?.legal && <li><span className='desc'>legal:</span><span className='text-[12px]'>{identity.legal}</span></li>}
Resolved, pls check

2023-07-04 17:36 UTC, sahas-01 commented
> Please check comments

Resolved, pls check

2023-07-05 10:49 UTC, merged

2023-07-05 15:39 UTC, rajdeep7Singh commented
Reverting this PR due to issues on Prod. Please check @This-Is-Prince
![Uploading Screenshot 2023-07-05 at 8.57.14 PM.png…]()