feat: hover on username
polkassembly/polkassembly pull request #394
Opened 2023-07-06 13:03 UTC by sahas-01

Hovering on username updated as per the designs.

2023-07-11 05:50 UTC, alphainfinitus approved these changes

2023-07-14 06:31 UTC, alphainfinitus commented on src/ui-components/IdentityBadge.tsx
> +		{identity?.pgp &&
no pgp icon

2023-07-14 06:33 UTC, alphainfinitus commented on src/ui-components/IdentityBadge.tsx
> +		{identity?.pgp &&
spy icon

2023-07-14 06:33 UTC, alphainfinitus commented on src/ui-components/IdentityBadge.tsx
> +			<span className='desc text-bodyBlue font-medium text-sm'>Council member: </span><CouncilEmoji/>
Council emoji should be first

2023-07-14 06:33 UTC, alphainfinitus requested changes
Please check comments

2023-07-14 08:52 UTC, sahas-01 commented on src/ui-components/IdentityBadge.tsx
> +			<span className='desc text-bodyBlue font-medium text-sm'>Council member: </span><CouncilEmoji/>
Resolved, pls check

2023-07-14 09:12 UTC, sahas-01 commented on src/ui-components/IdentityBadge.tsx
> +		{identity?.pgp &&
Added, pls check

2023-07-14 16:59 UTC, alphainfinitus requested changes
Please check comments

2023-07-14 17:04 UTC, sahas-01 commented on src/ui-components/IdentityBadge.tsx
> +			<span className='desc text-bodyBlue font-medium text-sm'><CouncilEmoji /> Council member: </span>
Done, pls check

2023-07-14 17:09 UTC, alphainfinitus approved these changes

2023-07-18 10:50 UTC, merged