Pa footer
polkassembly/polkassembly pull request #482
Opened 2023-07-27 10:48 UTC by Lt-Kartik-9PARA-SF

2023-07-28 14:43 UTC, alphainfinitus commented on src/components/AppLayout/Footer.tsx
> +								{
we don't need these curly braces here

2023-07-28 14:44 UTC, alphainfinitus commented on src/components/AppLayout/Footer.tsx
> +							<p className="text-lg font-bold text-[#243A57] mb-[-5px] max-[650px]:mt-[-15px] ">Our Services</p>
please remove arbitrary colour values

2023-07-28 14:44 UTC, alphainfinitus commented on src/components/AppLayout/Footer.tsx
> +				<div className="mt-5 pb-3 text-sm text-[#485F7D] font-medium">
please remove arbitrary text colour

2023-07-28 14:45 UTC, alphainfinitus commented on src/components/AppLayout/Footer.tsx
> +							{
do not need curly braces here

2023-07-28 14:47 UTC, alphainfinitus commented on src/components/AppLayout/Footer.tsx
> +				<div className='md:hidden'>
we don't need whole another  div for small devices, can be done in the div above

2023-07-28 14:47 UTC, alphainfinitus requested changes
Please check comments.

2023-07-31 15:42 UTC, KanishkaRajputd approved these changes

2023-07-31 17:19 UTC, merged